version: '3.8'

services:
  mysqli:
    container_name: mysqli
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_ROOT_DATABASE=rootdb
    ports:
      - 3306:3306
  app:
    build: .
    depends_on:
      - mysqli
    links:
      - mysqli
    ports:
      - 3000:3000